name: footprint3
description: "A new Flutter project."

version: 1.1.7+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.20.2
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  google_mlkit_document_scanner: ^0.4.0
  timelines: ^0.1.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  html: ^0.15.6
  universal_html: ^2.2.4
  ai_barcode_scanner: ^6.0.1
  camera_web: ^0.3.5
  camera: ^0.11.1
  webview_flutter: ^4.13.0
  flutter_native_splash: ^2.4.6


  # firebase_performance: ^0.10.1+6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo/iconOfficial.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - images/
     - images/logo/

  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Thin.ttf
        - asset: fonts/roboto/Roboto-Light.ttf

flutter_native_splash:
  color: "#121212"
  image: images/logo/iconOfficial.png

  android_12:
    image: images/logo/iconOfficial.png
    icon_background_color: "#121212"

  web: false